---

- hosts: ansible
  become: yes
  
  tasks:
    - name: "Add Apt Repo for Ansible"
      apt_repository:
        repo: "ppa:ansible/ansible"
        state: present
        update_cache: yes

    - name: "Install Apt Packages"
      apt:
        pkg:
        - git
        - python3
        - software-properties-common
        - ansible

