---

- hosts: jekyll
  become: yes

  tasks:
    - name: "Install Apt Packages"
      apt:
        force_apt_get: yes
        pkg:
        - git
        - open-vm-tools
        - ruby-full
        - build-essential
        - zlib1g-dev
        - openjdk-8-jdk

    - name: "Install Jekyll"
      command: sudo gem install jekyll -N

    - name: "Install Bundle"  
      command: sudo gem install bundler -N

    - name: "Install s3_website"
      command: sudo gem install s3_website -N

    - name: "First run of s3_website"
      command: sudo s3_website install

    - name: "Update Ruby Gems"
      command: sudo gem update -N

    - name: "First run of s3_website"
      command: s3_website cfg create
      args:
        creates: s3_website.yml
        chdir: /home/server/website/website