---

- hosts: jekyll

  tasks:
    - name: "Install Apt Packages"
      become: yes
      apt:
        force_apt_get: yes
        pkg:
        - git
        - open-vm-tools
        - ruby-full
        - build-essential
        - zlib1g-dev
        - openjdk-8-jdk

    - name: "Install Bundler"
      gem:
        name: bundler
        state: latest

    - name: "Install Jekyll"
      gem:
        name: jekyll
        state: latest

    - name: "Install s3_website"
      gem:
        name: s3_website
        state: latest

    - name: "Pull Github Files"
      git:
        repo: https://github.com/s-k-hassan/website.git
        dest: /home/$USER/website
        accept_hostkey: yes
        force: yes

    - name: "First run of s3_website"
      command: s3_website cfg create
      args:
        creates: s3_website.yml
        chdir: /home/$USER/website