---

- hosts: docker
  become: yes
  vars:
    splunk_mount: "192.168.8.205:/volume2/container-data/splunk"
    data_mount: "192.168.8.205:/volume2/container-data/container-data"  


  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Mount Splunk-Data drive
      mount:
       path: /nfs/splunk
       src: {{ splunk_mount }}
       state: mounted
       fstype: ext4

    - name: Mount Container-Data drive
      mount:
        path: /nfs/container-data
        src: {{ data_mount }}
        state: mounted
        fstype: ext4