---

  - hosts: docker
    become: yes

    tasks:
      - name: Create Portainer Volume
        docker_volume:
          name: portainer_data

      - name: Start Portainer Image
        become: yes
        docker_container:
          name: Portainer
          state: started
          image: portainer/portainer:latest
          ports: 8001:8000
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
          tty: yes
          restart_policy: unless-stopped