---

  - hosts: docker
    become: yes
    vars:
      splunk_data_drive: "/nfs/splunk"

    tasks:
      - name: Start Splunk Image
        docker_container:
          name: splunk
          state: started
          image: splunk/splunk:latest
          ports: 8000:8000
          tty: yes
          restart_policy: unless-stopped
          volumes:
            - "{{  /nfs/splunk  }}": /opt/splunk/var
          env:
            SPLUNK_PASSWORD: "password"
            SPLUNK_START_ARGS: "--accept-license"


