---

- hosts: ansible
  become: yes
  
  tasks:
    - name: "Add Apt Repo for Ansible"
      apt_repository:
        repo: "ppa:ansible/ansible"
        state: present
        update_cache: yes

    - name: "Install Apt Packages"
      apt:
        pkg:
        - git
        - python3
        - software-properties-common
        - ansible

#    - name: "Generate SSH Key"
#      command: 'cat /dev/zero | ssh-keygen -q -N ""'
#      args:
#        creates: /home/server/.ssh/id_rsa

    - name: "Pull Github Files"
      git:
        repo: https://github.com/s-k-hassan/environments.git
        dest: /home/$USER/playbooks
        accept_hostkey: yes
        force: yes