---

- hosts: ubuntu
  become: yes
  gather_facts: true

  tasks:
    - name: Update repository cache
      apt:
        update_cache: yes

    - name: "Install Base Packages"
      apt:
        pkg:
        - open-vm-tools
        - resolvconf

    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest

    - name: Autoremove old packages
      apt:
        autoremove: yes